name: smstrap

description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.12.29

  auto_route: ^6.2.0

  bloc_concurrency: ^0.2.0

  cached_network_image: ^3.2.3

  connectivity_plus: ^3.0.3

  cupertino_icons: ^1.0.5

  dartz: ^0.10.1

  dio: ^5.1.1

  enough_platform_widgets: ^0.7.1

  firebase_analytics: ^10.2.0

  firebase_core: ^2.9.0

  firebase_crashlytics: ^3.1.0

  firebase_storage: ^11.0.15

  flutter_bloc: ^8.1.1

  flutter_local_notifications: ^13.0.0

  flutter_screenutil: ^5.7.0

  flutter_svg: ^1.1.6

  fluttertoast: ^8.1.2

  freezed_annotation: ^2.2.0

  get_it: ^7.2.0

  google_fonts: ^4.0.3

  hive_flutter:
    git:
      url: https://github.com/Flutter-Fox/hive.git
      ref: master
      path: hive_flutter/

  injectable: ^2.1.1

  internet_connection_checker: ^1.0.0+1

  intl: ^0.17.0

  json_annotation: ^4.8.0

  kt_dart: ^1.1.0

  modal_bottom_sheet: ^3.0.0-pre

  path_provider: ^2.0.2

  pretty_dio_logger: ^1.3.1

  retrofit: ^4.0.1

  rxdart: ^0.27.7

  sliver_tools: ^0.2.9

  stack_trace: ^1.10.0

  uuid: ^3.0.7

dependency_overrides:
  test_api: ^0.4.18

dev_dependencies:
  auto_route_generator: ^6.2.0

  bloc_test: ^9.1.0 # version solving fails when used with flutter_test

  build_runner: ^2.3.3

  build_verify: ^3.1.0

  cloud_firestore_odm_generator: ^1.0.0-dev.51

  easy_logger: ^0.0.2

  flutter_launcher_icons: ^0.12.0

  flutter_lints: ^2.0.1

  freezed: ^2.3.2

  hive_generator:
    git:
      url: https://github.com/Flutter-Fox/hive.git
      ref: master
      path: hive_generator/

  injectable_generator: ^2.1.5

  json_serializable: ^6.6.0

  logger: ^1.3.0

  mockito: ^5.3.2

  retrofit_generator:
    git:
      url: https://github.com/Flutter-Fox/retrofit.dart.git
      ref: ft/new/app_http_client
      path: generator/

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/raw/
